(part "ADP7158ARDZ-3_3-R7"
    (packageRef "SOIC127P600X175-9N")
    (interface
        (port "1" (symbPinId 1) (portName "VOUT") (portType OUTPUT))
        (port "2" (symbPinId 2) (portName "VOUT_SENSE") (portType INOUT))
        (port "3" (symbPinId 3) (portName "BYP") (portType INOUT))
        (port "4" (symbPinId 4) (portName "EN") (portType INPUT))
        (port "5" (symbPinId 5) (portName "REF_SENSE") (portType INOUT))
        (port "6" (symbPinId 6) (portName "REF") (portType INOUT))
        (port "7" (symbPinId 7) (portName "VREG") (portType INOUT))
        (port "8" (symbPinId 8) (portName "VIN") (portType POWER))
        (port "9" (symbPinId 9) (portName "GND") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "Analog Devices")
    (property "Manufacturer_Part_Number" "ADP7158ARDZ-3.3-R7")
    (property "Mouser_Part_Number" "584-ADP7158ARDZ3.3R7")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Analog-Devices/ADP7158ARDZ-3.3-R7?qs=JeIcUl65ClBbLSN64Y7owQ%3D%3D")
    (property "Arrow_Part_Number" "ADP7158ARDZ-3.3-R7")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/adp7158ardz-3.3-r7/analog-devices?utm_currency=USD&region=nac")
    (property "Description" "LDO Voltage Regulators 3.3/5Vin 1.2A Ultra Low Noise LDO Fixed")
    (property "Datasheet_Link" "https://componentsearchengine.com/Datasheets/1/ADP7158ARDZ-3.3-R7.pdf")
    (property "symbolName1" "ADP7158ARDZ-3_3-R7")
)
