(part "RC0402FR-0710KL"
    (packageRef "RESC1005X40N")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "131")
    (property "Manufacturer_Name" "KEMET")
    (property "Manufacturer_Part_Number" "RC0402FR-0710KL")
    (property "Mouser_Part_Number" "603-RC0402FR-0710KL")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/YAGEO/RC0402FR-0710KL?qs=I1mnnYJTTsxUoNwrUsQExA%3D%3D")
    (property "Arrow_Part_Number" "RC0402FR-0710KL")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/rc0402fr-0710kl/yageo?region=europe")
    (property "Description" "YAGEO (PHYCOMP) - RC0402FR-0710KL. - RES, THICK FILM, 10K, 1%, 0.0625W, 0402")
    (property "Datasheet_Link" "http://www.yageo.com/documents/recent/PYu-RC0402_51_RoHS_L_6_r.pdf")
    (property "symbolName1" "RC0402FR-0710KL")
)
