(part "SS-5GLD2"
    (packageRef "SS5GLD2")
    (interface
        (port "1" (symbPinId 1) (portName "COM") (portType INOUT))
        (port "2" (symbPinId 2) (portName "NO") (portType INOUT))
        (port "3" (symbPinId 3) (portName "NC") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "162")
    (property "Manufacturer_Name" "OMRON Electronics")
    (property "Manufacturer_Part_Number" "SS-5GLD2")
    (property "Mouser_Part_Number" "653-SS-5GLD2")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Omron-Electronics/SS-5GLD2?qs=1tDaWCEHQQ5Kjmt2FsnuUw%3D%3D")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "Microswitch, Subminiature, Hinge Roller Lever, SPDT, Through Hole, 5 A Current Rating (Amps)   5A (AC)")
    (property "Datasheet_Link" "https://omronfs.omron.com/en_US/ecb/products/pdf/en-ss.pdf")
    (property "symbolName1" "SS-5GLD2")
)
