(part "CL21A476MQYNNNE"
    (packageRef "CAPC2012X135N")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "32")
    (property "Manufacturer_Name" "SAMSUNG")
    (property "Manufacturer_Part_Number" "CL21A476MQYNNNE")
    (property "Mouser_Part_Number" "187-CL21A476MQYNNNE")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Samsung-Electro-Mechanics/CL21A476MQYNNNE?qs=yOVawPpwOwkBQMdcEdF9JA%3D%3D")
    (property "Arrow_Part_Number" "CL21A476MQYNNNE")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/cl21a476mqynnne/samsung-electro-mechanics?region=nac")
    (property "Description" "Cap Ceramic 47uF 6.3V X5R 20% Pad SMD 0805 85C T/R")
    (property "Datasheet_Link" "https://media.digikey.com/pdf/Data%20Sheets/Samsung%20PDFs/CL_Series_MLCC_ds.pdf")
    (property "symbolName1" "CL21A476MQYNNNE")
)
